### ISSUE TITLE
Exception after running Main in ExampleApp in package iad.cluster

### ISSUE THREAD

**Issue by hubigabi** [glbwsk/iad#1]
I cloned  this repository and run without any changes Main in ExampleApp in package iad.cluster
I got this Exception:

```java
java.io.IOException: Cannot run program "gnuplot": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at iad.cluster.common.Utils.rumCmd(Utils.java:45)
	at iad.cluster.NeuralGas.calc(NeuralGas.java:74)
	at iad.cluster.ExampleApp.txt(ExampleApp.java:53)
	at iad.cluster.ExampleApp.main(ExampleApp.java:13)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 7 more
0
1
2
3
...
997
998
999
javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at iad.cluster.common.FileHandler.compareImg(FileHandler.java:248)
	at iad.cluster.ExampleApp.main(ExampleApp.java:15)
Exception in thread "main" java.lang.NullPointerException
	at iad.cluster.common.FileHandler.compareImg(FileHandler.java:253)
	at iad.cluster.ExampleApp.main(ExampleApp.java:15)
```

**Comment by lukago** [comment]
Hi, you need to have gnuplot installed and added to your OS path

**Comment by hubigabi** [comment]
Thanks for a fast response, really appreciate it. After installing gnuplot and adding to Eniverement Variable (Windows 10) the first exception is gone. The second problem is still here, probably caused by this line;

```java
FileHandler.compareImg("images/lenakolor3.jpg", "images/l3.jpg");
```
I checked and in **.gitignore** directory **images** is added. Do you know how could I generate these image files?

**Comment by lukago** [comment]
You can use any images which you want to compare for similarity
